routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BukuController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/buku');

Route::resource('buku', BukuController::class);

app/Models/Buku.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Buku extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BukuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Models\Buku;

class BukuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bukus = Buku::latest()->paginate(2);
        return view('index', compact('bukus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'cover' => 'required|image|mimes:png, jpg, jpeg',
            'judul' => 'required',
            'penulis' => 'required',
            'tahun_terbit' => 'required',
        ]);

        $cover = $request->file('cover');
        $cover->storeAs('public/buku', $cover->hashName());

        $buku = new Buku();
        $buku->judul = $request->judul;
        $buku->penulis = $request->penulis;
        $buku->tahun_terbit = $request->tahun_terbit;
        $buku->cover = $cover->hashName();
        $buku->save();

        if ($buku) {
            return redirect()->route('buku.index')->with(['sukses' => 'Buku berhasil disimpan']);
        } else {
            return redirect()->route('buku.index')->with(['gagal' => 'Buku gagal disimpan']);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/create.blade.php
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    
    <title>Tambah Buku</title>
  </head>
  <body style="background: #f1f1f1">
    <div class="container nt-5">
      <div class="row">
        <div class="col-md-12">
          <div class="card border-0 shadow rounded">

            <div class="card-header">
              <h4 class="text-center">
                <i class="bi bi-book"></i> Tambah Buku
              </h4>
            </div>

            <div class="card-body">
                <form action="{{ route('buku.store') }}" method="post" enctype="multipart/form-data" autocomplete="off">
                    @csrf

                    <div class="form-group">
                        <label for="Judul" class="fw-bold"></label>
                        <input type="text" class="form-control" placeholder="Judul" value="{{ old('Judul')}}" name="judul">
                        @error('Judul')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror 
                    </div>

                    <div class="form-group">
                        <label for="Penulis" class="fw-bold"></label>
                        <input type="text" class="form-control" placeholder="Penulis" value="{{ old('Penulis')}}" name="penulis">
                        @error('Penulis')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror 
                    </div>

                    <div class="form-group">
                        <label for="Tahun" class="fw-bold">Tahun</label>
                        <input type="text" class="form-control" placeholder="Tahun" value="{{ old('Tahun')}}" name="tahun_terbit">
                        @error('Tahun_Terbit')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror 
                    </div>

                    <div class="from-danger mt-2">
                      <div style="widht:200px">
                        <img src ="{{ Storage::url('public/buku/default.jpg') }}" class="img-fluid img-thumbnail" id="preview">
                      </div>
                    </div>

                    <div class="form-group">
                        <label for="cover" class="fw-fold">Cover</label>
                        <input type="file" name="cover" class="form-control">
                        @error('cover')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror 
                    </div>

                    <div class="form-group d-flex justify-content-end mt-3">
                      <a href="{{ route('buku.index') }}" class="btn btn-outline-secondary mx-2">Batal</a>
                      <button type="submit" class="btn btn-primary"><i class="bi bi-sd-card"></i>Simpan</button>
                    </div>
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $('input[type=file]').on('change', function(e) {
          var reader = new FileReader();
          reader.onload = function(e) {
            $('#preview').attr('src', e.target.result);
          }
          reader.readAsDataURL(this.files[0]);
        });
    </script>
  </body>
</html>

resources/views/index.blade.php
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    
    <title>Daftar Buku</title>
  </head>
  <body style="background: #f1f1f1">
    <div class="container nt-5">
      <div class="row">
        <div class="col-md-12">
          <div class="card border-0 shadow rounded">

            <div class="card-header">
              <h4 class="text-center">
                <i class="bi bi-book"></i> Daftar Buku
              </h4>
            </div>

            <div class="card-body">
              <a href="{{ route('buku.create') }}" class="btn btn-primary"><i class="bi bi-plus-square-dotted"></i>Tambah Buku</a>
              <table class="table table-bordered table-striped mt-2">
                <thead class="text-center">
                    <th style="width:50px">No</th>
                    <th style="width:200px">Cover</th>
                    <th>Judul</th>
                    <th>Penulis</th>
                    <th>Tahun Terbit</th>
                    <th style="width:200px"></th>
                </thead>
                <tbody>
                    @forelse($bukus as $i) => $buku
                        <tr>
                          <td class="text-center">{{ $i + 1 }}</td>
                          <td class="text-center">
                            @if(Storage::disk('local')->exists('public/buku/'.$buku))
                                <img src="{{ Storage::url('public/buku').$buku->cover}}" class="img-fluid img-thumbnail">
                            @else
                                <img src="{{ Storage::url('public/buku/default.jpg').$buku->cover}}" class="img-fluid img-thumbnail">
                            @endif
                          </td>
                          <td>{{ $buku->judul }}</td>
                          <td>{{ $buku->penulis }}</td>
                          <td>{{ $buku->tahun_terbit }}</td>
                          <td class="text-center">
                            <a href="" class="btn btn-sm btn-outline-secondary"><i class="bi bi-pencil-square"></i>Edit</a>
                            <button type="button" class="btn btn-sm btn-outline-secondary"><i class="bi bi-trash"></i>Hapus</button>
                          </td>
                        </tr>

                    @empty
                      <tr>
                        <td>
                          <div class="alert alert-info">Data Buku tidak tersedia</div>
                        </td>
                      </tr>


                    @endforelse
                </tbody>
              </table>

              {{ $bukus->links() }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
      @if(Session::has('sukses'))
        toastr.success("{{ Session::get('sukses')}}", "Berhasil");
      @endif
      @if(Session::has('gagal'))
        toastr.error("{{ Session::get('gagal')}}", "Gagal");
      @endif
    </script>
    
  </body>
</html>